import type { ActionDef } from "./types";

export const SKILL_LABEL: Record<string, string> = {
  wahrnehmung: "Wahrnehmung",
  intuition: "Intuition",
  charme: "Charme",
  feilschen: "Feilschen",
  bestechen: "Bestechen",
  einschuechtern: "Einschüchtern",
  klatsch: "Klatsch",
  schleichen: "Schleichen",
  nahkampf: "Nahkampf",
  ausweichen: "Ausweichen",
  athletik: "Athletik",
  ausdauer: "Ausdauer",
  besonnenheit: "Besonnenheit",
  fingerfertigkeit: "Fingerfertigkeit",
};

export const CATALOG: ActionDef[] = [
  {
    id: "umschauen",
    label: "Umschauen",
    cost: "H",
    tab: "sozial",
    skill: "wahrnehmung",
    resolver: "simple",
    summary: "Den Ort und die Leute mit den Augen abtasten.",
    ask: "Mich umschauen",
  },
  {
    id: "intuition",
    label: "Einschätzen",
    cost: "H",
    tab: "sozial",
    skill: "intuition",
    resolver: "simple",
    summary: "Absicht und Haltung eines Gegenübers lesen.",
    ask: "Die Lage einschätzen",
  },
  {
    id: "reden",
    label: "Ansprechen / Verhandeln",
    cost: "H",
    tab: "sozial",
    skill: "charme",
    resolver: "simple",
    summary: "Mit Worten überzeugen, schmeicheln, Vertrauen suchen.",
    ask: "Jemanden ansprechen",
  },
  {
    id: "feilschen",
    label: "Handeln",
    cost: "H",
    tab: "sozial",
    skill: "feilschen",
    resolver: "opposed",
    summary: "Den Preis drücken. Vergleich gegen den Händler.",
    ask: "Um den Preis feilschen",
  },
  {
    id: "bestechen",
    label: "Bestechen",
    cost: "H",
    tab: "sozial",
    skill: "bestechen",
    resolver: "simple",
    summary: "Geld oder Gefälligkeit gegen ein Entgegenkommen.",
    ask: "Bestechen",
  },
  {
    id: "einschuechtern",
    label: "Einschüchtern",
    cost: "H",
    tab: "sozial",
    skill: "einschuechtern",
    resolver: "opposed",
    summary: "Drohen. Status färbt die Konsequenz, nicht die Karte.",
    ask: "Einschüchtern",
  },
  {
    id: "klatsch",
    label: "Gerüchte",
    cost: "H",
    tab: "sozial",
    skill: "klatsch",
    resolver: "simple",
    summary: "In der Menge nach Geschichten und Preisen fischen.",
    ask: "Nach Gerüchten fragen",
  },
  {
    id: "kaufen",
    label: "Kaufen",
    cost: "H",
    tab: "sozial",
    skill: "feilschen",
    resolver: "opposed",
    summary: "Zuerst zahlen, dann Feilschen um den Preis. Verfügbarkeit entscheidet der SL.",
    ask: "Kaufen",
  },
  {
    id: "schleichen",
    label: "Schleichen",
    cost: "BH",
    tab: "bewegung",
    skill: "schleichen",
    resolver: "simple",
    summary: "Unbemerkt bleiben oder sich davonstehlen.",
  },
  {
    id: "gehen",
    label: "Gehen",
    cost: "B",
    tab: "bewegung",
    resolver: "move",
    summary: "An einen genannten Ort der Szene oder einen Ausgang. Im Kampf: Bewegung × 2 Meter. Kein Wurf.",
    ask: "Woanders hingehen",
  },
  {
    id: "warten",
    label: "Abwarten",
    cost: "H",
    tab: "bewegung",
    resolver: "auto",
    summary: "Stillstehen, beobachten, die Frist verstreichen lassen.",
    ask: "Abwarten",
  },
  {
    id: "sprinten",
    label: "Sprinten",
    cost: "H",
    tab: "bewegung",
    skill: "athletik",
    resolver: "simple",
    summary: "Volle Bewegung. Im Kampf eine Handlung.",
  },
  {
    id: "fliehen",
    label: "Fliehen",
    cost: "B",
    tab: "bewegung",
    skill: "athletik",
    resolver: "combat",
    summary: "Aus dem Kampf. Gebunden: freie Attacke des Gegners.",
  },
  {
    id: "aufstehen",
    label: "Aufstehen",
    cost: "B",
    tab: "bewegung",
    resolver: "auto",
    summary: "Den Zustand Niedergestreckt beenden.",
  },
  {
    id: "kriechen",
    label: "Kriechen",
    cost: "B",
    tab: "bewegung",
    resolver: "move",
    summary: "Halbe Bewegung, solange du niedergestreckt bist.",
  },
  {
    id: "waffe_ziehen",
    label: "Waffe ziehen",
    cost: "F",
    tab: "kampf",
    resolver: "auto",
    summary: "Den Dolch oder die geführte Waffe ziehen. Eskaliert die Szene.",
    ask: "Die Waffe ziehen",
  },
  {
    id: "angreifen",
    label: "Angreifen",
    cost: "H",
    tab: "kampf",
    skill: "nahkampf",
    resolver: "combat",
    summary: "Vergleichender Wurf. Meist Nahkampf gegen Nahkampf oder Ausweichen.",
    ask: "Angreifen",
  },
  {
    id: "sturmangriff",
    label: "Sturmangriff",
    cost: "BH",
    tab: "kampf",
    skill: "nahkampf",
    resolver: "combat",
    summary: "Bewegung + Handlung, +1 Vorteil, Bindung.",
  },
  {
    id: "loesen",
    label: "Aus Bindung lösen",
    cost: "H",
    tab: "kampf",
    skill: "ausweichen",
    resolver: "combat",
    summary: "Wurf oder Vorteilsvorsprung ausgeben.",
  },
  {
    id: "volle_abwehr",
    label: "Nur verteidigen",
    cost: "H",
    tab: "kampf",
    skill: "ausweichen",
    resolver: "combat",
    summary: "Die Handlung der Abwehr opfern. Nächster Vergleich zu deinen Gunsten.",
  },
  {
    id: "ausweichen",
    label: "Attacke ausweichen",
    cost: "F",
    tab: "kampf",
    skill: "ausweichen",
    resolver: "combat",
    summary: "Keine eigene Handlung. Verteidigung gegen den nächsten Schlag.",
  },
  {
    id: "glueck",
    label: "Glückspunkt",
    cost: "F",
    tab: "ressourcen",
    resolver: "resource",
    summary: "Eigenen Wurf wiederholen oder +1 EG. Nur im Glück-Fenster.",
  },
  {
    id: "mut",
    label: "Mutpunkt",
    cost: "F",
    tab: "ressourcen",
    resolver: "resource",
    summary: "Einen Zustand entfernen. Bei Niedergestreckt zusätzlich +1 LP.",
  },
  {
    id: "schicksal",
    label: "Schicksal opfern",
    cost: "F",
    tab: "ressourcen",
    resolver: "resource",
    summary: "Nicht sterben / die Szene überleben. Permanent.",
  },
  {
    id: "zaehigkeit",
    label: "Zähigkeit",
    cost: "F",
    tab: "ressourcen",
    resolver: "resource",
    summary: "Wurf selbst wählen oder Mutation vermeiden. Permanent.",
  },
  {
    id: "freitext",
    label: "Bitte an den SL",
    cost: "H",
    tab: "sozial",
    resolver: "simple",
    summary: "Keine alleinige Steuerung. Der SL hängt sie an eine Fähigkeit oder lehnt ab.",
    ask: "Etwas anderes versuchen",
  },
];

export const CATALOG_BY_ID: Record<string, ActionDef> = Object.fromEntries(
  CATALOG.map((a) => [a.id, a]),
);

export function actionAsk(def: ActionDef): string {
  return def.ask ?? def.label;
}

export const SOCIAL_FAIL_IDS = new Set([
  "reden",
  "feilschen",
  "bestechen",
  "einschuechtern",
  "klatsch",
]);
