/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BogenRouteImport } from './routes/bogen'
import { Route as ErschaffungRouteImport } from './routes/erschaffung'
import { Route as SlRouteImport } from './routes/sl'
import { Route as TischRouteImport } from './routes/tisch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BogenRoute = BogenRouteImport.update({
  id: '/bogen',
  path: '/bogen',
  getParentRoute: () => rootRouteImport,
} as any)
const ErschaffungRoute = ErschaffungRouteImport.update({
  id: '/erschaffung',
  path: '/erschaffung',
  getParentRoute: () => rootRouteImport,
} as any)
const SlRoute = SlRouteImport.update({
  id: '/sl',
  path: '/sl',
  getParentRoute: () => rootRouteImport,
} as any)
const TischRoute = TischRouteImport.update({
  id: '/tisch',
  path: '/tisch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bogen': typeof BogenRoute
  '/erschaffung': typeof ErschaffungRoute
  '/sl': typeof SlRoute
  '/tisch': typeof TischRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bogen': typeof BogenRoute
  '/erschaffung': typeof ErschaffungRoute
  '/sl': typeof SlRoute
  '/tisch': typeof TischRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bogen': typeof BogenRoute
  '/erschaffung': typeof ErschaffungRoute
  '/sl': typeof SlRoute
  '/tisch': typeof TischRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bogen' | '/erschaffung' | '/sl' | '/tisch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bogen' | '/erschaffung' | '/sl' | '/tisch'
  id: '__root__' | '/' | '/bogen' | '/erschaffung' | '/sl' | '/tisch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BogenRoute: typeof BogenRoute
  ErschaffungRoute: typeof ErschaffungRoute
  SlRoute: typeof SlRoute
  TischRoute: typeof TischRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bogen': {
      id: '/bogen'
      path: '/bogen'
      fullPath: '/bogen'
      preLoaderRoute: typeof BogenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erschaffung': {
      id: '/erschaffung'
      path: '/erschaffung'
      fullPath: '/erschaffung'
      preLoaderRoute: typeof ErschaffungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl': {
      id: '/sl'
      path: '/sl'
      fullPath: '/sl'
      preLoaderRoute: typeof SlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tisch': {
      id: '/tisch'
      path: '/tisch'
      fullPath: '/tisch'
      preLoaderRoute: typeof TischRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BogenRoute: BogenRoute,
  ErschaffungRoute: ErschaffungRoute,
  SlRoute: SlRoute,
  TischRoute: TischRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
